linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/pterm/pterm.SpinnerPrinter).Stop
      - (github.com/pterm/pterm.TablePrinter).Render

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

